---

- name: Prepare Server for application deployment
  connection: ssh
  gather_facts: true
  hosts: all
  become: true
  roles:
    - geerlingguy.docker
  
  pre_tasks:
  - name: Ensure Python 3 is installed
    ansible.builtin.raw: apt-get update && apt-get install -y python3