---

- name: Prepare Server for application deployment
  connection: ssh
  gather_facts: true
  hosts: all
  become: true
  
  tasks:
  - name: Ensure Python 3 is installed
    ansible.builtin.raw: apt-get update && apt-get install -y python3

  - name: Install ca-certificates & curl (both prerequisites for docker install)
    ansible.builtin.apt:
      name: 
        - ca-certificates
        - curl

  - name: Create /etc/apt/keyrings directory
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: "0755"

  - name: Download Docker GPG key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: "a+r"

  - name: Add Docker APT repository
    ansible.builtin.apt_repository:
      repo: >-
        deb [signed-by=/etc/apt/keyrings/docker.asc]
        https://download.docker.com/linux/ubuntu
        {{ ansible_distribution_release }} stable
      filename: docker
      state: present
      update_cache: true

  - name: Install Docker packages
    ansible.builtin.apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present



